name: lrui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  animations: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/font/SF-Pro-Display-Black.ttf
        - asset: assets/font/SF-Pro-Display-Bold.ttf
        - asset: assets/font/SF-Pro-Display-Light.ttf
        - asset: assets/font/SF-Pro-Display-Medium.ttf
        - asset: assets/font/SF-Pro-Display-Regular.ttf
        - asset: assets/font/SF-Pro-Display-Semibold.ttf
        - asset: assets/font/SF-Pro-Display-Thin.ttf
        - asset: assets/font/SF-Pro-Display-Ultralight.ttf
